name: LCPlugin
main: com.github.djlc.LCPlugin
version: 0.0.1
depend: [Vault]

commands:
  cube:
    description: Create a n^3 cube. It costs $n^3.
    usage: /<command> [Size] [Block Name]
    permission: lcplugin.cube
    permission-message: You don't have <permission>
