name: LCPlugin
main: com.github.djlc.LCPlugin
version: 0.0.1
depend: [Vault]

commands:
  cube:
    description: Create a n^3 cube by your hand's Blocks. It costs $n^3.
    usage: /<command> [Size]
    permission: lcplugin.cube
    permission-message: You don't have <permission>
  iteminfo:
    description: get item information in your main hand.
    usage: /<command>
    permission: lcplugin.iteminfo
    permission-message: You don't have <permission>
  date:
    description: get date now.
    usage: /<command>
    permission: lcplugin.date
    permission-message: You don't have <permission>
